server/phoenix/cookbk/lib/cookbk_web/router.ex
defmodule CookbkWeb.Router do
  use CookbkWeb, :router
  import Plug.BasicAuth
  import Phoenix.LiveView.Router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {CookbkWeb.LayoutView, :root}
    plug :debug
  end


  # TODO: make admin password env var
  pipeline :admins_only do
    plug :basic_auth, username: "admin", password: "secret_admin_password"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CookbkWeb do
    pipe_through :browser


    get "/", PageController, :index

    resources "/users", UserController do
      pipe_through [:authenticate_user]

      scope "/meal" do
        get "/form", MealController, :form
        post "/make", MealController, :make
        get "/results", MealController, :results
      end

      resources "/recipes", RecipeController
    end

    resources "/sessions", SessionController,
      only: [:new, :create, :delete],
      singleton: true

    live "/thermostat", ThermostatLive
  end

  # Other scopes may use custom stacks.
  # scope "/api", CookbkWeb do
  #   pipe_through :api
  # end

  scope "/" do
    pipe_through [:browser, :admins_only]
    live_dashboard "/dashboard"
  end

  # TODO: baaaaad code duplication
  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, "Login required")
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()

      user_id ->
        assign(conn, :current_user, Cookbk.Accounts.get_user!(user_id))
    end
  end

  defp debug(conn, _) do
    assign(conn, :debug, Application.get_env(:cookbk, :debug, false))
  end
end

server/phoenix/cookbk/lib/cookbk/accounts/user.ex
defmodule Cookbk.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Cookbk.Accounts.Credential
  alias Cookbk.Meals.Recipe

  schema "users" do
    field :username, :string
    has_one :credential, Credential
    has_many :recipes, Recipe

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username])
    |> validate_required([:username])
    |> unique_constraint(:username)
  end
end

server/phoenix/cookbk/lib/cookbk_web/controllers/user_controller.ex
defmodule CookbkWeb.UserController do
  use CookbkWeb, :controller

  alias Cookbk.Accounts
  alias Cookbk.Accounts.User

  plug :authenticate_user when action not in [:new, :create, :index]

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  # TODO: baaaaad duplicate code
  # How can I share with router.ex?
  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, "Login required")
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()

      user_id ->
        assign(conn, :current_user, Cookbk.Accounts.get_user!(user_id))
    end
  end
end

server/phoenix/cookbk/lib/cookbk_web/views/user_view.ex
defmodule CookbkWeb.UserView do
  use CookbkWeb, :view
end

server/phoenix/cookbk/lib/cookbk_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

server/phoenix/cookbk/lib/cookbk_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <div class="form-group">
    <%= inputs_for f, :credential, fn cf -> %>
      <%= label cf, :email %>
      <%= text_input cf, :email %>
      <%= error_tag cf, :email %>
    <% end %>
  </div>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

server/phoenix/cookbk/lib/cookbk_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.credential.email %></td>

      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

server/phoenix/cookbk/lib/cookbk_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

server/phoenix/cookbk/lib/cookbk_web/templates/user/show.html.eex
<h1>User Profile</h1>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.credential.email %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>
<span><%= link "Recipes", to: Routes.user_recipe_path(@conn, :index, @user) %></span>